name: Docker Build and Push

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  docker-build:
    strategy:
      matrix:
        include:
          - package: service
            image: post-service
          - package: certifier
            image: certifier-service

    runs-on: ubuntu-24.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.package }}/Dockerfile
          push: true
          tags: spacemeshos/${{ matrix.image }}:latest, spacemeshos/${{ matrix.image }}:${{ GITHUB.SHA  }}, spacemeshos/${{ matrix.image }}:${{ github.ref_name }}
